import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import "@/fonts/fonts.css";
import "./globals.css";

export const metadata = {
  title: "New Govt. Degree College",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
    apple: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-kalpurush">
        <div className="container overflow-x-hidden">
          <Header />
          <Navbar />
          <div className="mb-12 mt-8 grid grid-cols-1 gap-8 md:grid-cols-[9fr_3fr]">
            <main>{children}</main>
            <Sidebar />
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
